Jonnitto:
  Sitemap:
    collection: '[instanceof Neos.Neos:Document][!instanceof Jonnitto.Sitemap:RemoveFromSitemap]'
    robotsTxt:
      dimensionsPresets: null

Neos:
  Neos:
    fusion:
      autoInclude:
        Jonnitto.Sitemap: true
  Flow:
    mvc:
      routes:
        'Jonnitto.Sitemap':
          position: 'start'
          variables:
            xmlSitemapPath: 'sitemap.xml'
