
Jonnitto:
  Sitemap:
    collection: '[instanceof Neos.Neos:Document][!instanceof Jonnitto.Sitemap:RemoveFromSitemap]'
Neos:
  Neos:
    typoScript:
      autoInclude:
        Jonnitto.Sitemap: true
