TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.Sitemap': TRUE

Jonnitto:
  Sitemap:
    collection: '[instanceof TYPO3.Neos:Document][!instanceof TYPO3.Neos:Shortcut]'
    defaultPriority: 0.5
