TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.Sitemap': TRUE

Jonnitto:
  Sitemap:
    filter: 'TYPO3.Neos:Document'
    maximumLevels: 999
    renderHiddenInIndex: TRUE
    removeNodeFromSitemap: '[instanceof TYPO3.Neos:Shortcut]'
    page: '[instanceof TYPO3.Neos.NodeTypes:Page]'
    pageSection: '[!instanceof TYPO3.Neos.NodeTypes:Page]'
    seperator:
      first: '!/'
      descend: '/'
