TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.Sitemap': true

Jonnitto:
  Sitemap:
    collection: '[instanceof TYPO3.Neos:Document][!instanceof Jonnitto.Sitemap:RemoveFromSitemap]'
